version: '3.8'


services:
  app:
    build: .
    volumes:
      - ./files_input:/wd/files_input:ro
      - ./files_output:/wd/files_output:rw
      - ./files_output:/wd/special_folder:rw
    user: "501"